site_name: IRIS GPU Bench
theme:
  name: 'material'
  features:
    - navigation.tabs
    - navigation.sections
   # - toc.integrate
    - navigation.top
    - navigation.trail
    - navigation.expand
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search

nav:
  - Index: docs/index.md
  - Overview: docs/overview.md
  - Installation: docs/installation.md
  - Building Benchmark Docker Images: docs/building_docker_images.md
  - Command-Line Interface: docs/command_line_interface.md
  - Example Commands: docs/example_commands.md
  - Collecting Results: docs/collecting_results.md
  - Live Monitoring: docs/live_monitoring.md
  - Considerations On Accuracy: docs/considerations_on_accuracy.md
  - Build Documentation: docs/build_docs.md
  - Work To Do: docs/work_to_do.md


extra_css:
  - 'docs/extra.css'