site_name: GPU Monitoring And Carbon Calculation Tool For Containerized Benchmarks
theme:
  name: 'material'
nav:
  - Home: overview.md
  - Index: index.md
  - Installation: installation.md
  - Building Docker Images: building_docker_images.md
  - Command-Line Arguments: command_line_arguments.md
  - Example Commands: example_commands.md
  - Results: results.md
  - Live Monitoring: live_monitoring.md
  - Considerations On Accuracy: considerations_on_accuracy.md
  - Work To Do: work_to_do.md
