name: CI
# contains jobs which run on every pull request
on:
  push:
    paths:
      - 'dockerfiles/**'
  pull_request:
    paths:
      - 'dockerfiles/**'
  workflow_dispatch:

jobs:

  build-base-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: mantid_base, dockerfile: dockerfiles/base_images/Dockerfile.mantid_base}
          - {name: sciml_base, dockerfile: dockerfiles/base_images/Dockerfile.sciml_base}
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: harbor.stfc.ac.uk
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: Build and Push Base Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: harbor.stfc.ac.uk/stfc-cloud-staging/iris-bench/${{ matrix.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-app-images:
    needs: build-base-images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: mnist_tf_keras, dockerfile: dockerfiles/app_images/sciml_bench/Dockerfile.mnist_tf_keras}
          - {name: stemdl_classification, dockerfile: dockerfiles/app_images/sciml_bench/Dockerfile.stemdl_classification}
          - {name: synthetic_regression, dockerfile: dockerfiles/app_images/sciml_bench/Dockerfile.synthetic_regression}
          - {name: mantid_run_1, dockerfile: dockerfiles/app_images/mantid_bench/Dockerfile.mantid_run_1}
          - {name: mantid_run_8, dockerfile: dockerfiles/app_images/mantid_bench/Dockerfile.mantid_run_8}
          - {name: dummy, dockerfile: dockerfiles/app_images/Dockerfile.dummy}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: harbor.stfc.ac.uk
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: Build and Push App Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: harbor.stfc.ac.uk/stfc-cloud-staging/iris-bench/${{ matrix.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.13.1
      uses: actions/setup-python@v1
      with:
              python-version: 3.13.1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        find . -name '*.py' -exec pylint {} \;

