name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'Benchmark_Docker/Benchmark_Dockerfiles/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Change to the directory where Dockerfiles are located
      - name: Change working directory
        run: cd Benchmark_Docker/Benchmark_Dockerfiles

      # Step 5: Build and Push the Docker Images
      - name: Build and Push Docker Images
        run: |
          IMAGE_PREFIX=ghcr.io/${{ github.repository }}/

          # Build and push gpu_base
          docker buildx build --push --tag $IMAGE_PREFIX/gpu_base:latest -f Dockerfile.gpu_base .

          # Build and push sciml_base
          docker buildx build --push --tag $IMAGE_PREFIX/sciml_base:latest -f sciml_benchmarks/Dockerfile.sciml_base .

          # Build and push mantid_base
          docker buildx build --push --tag $IMAGE_PREFIX/mantid_base:latest -f mantid_imaging_benchmarks/Dockerfile.mantid_base .

          # Build and push stemdl_classification_base
          docker buildx build --push --tag $IMAGE_PREFIX/stemdl_classification_base:latest -f sciml_benchmarks/Dockerfile.stemdl_classification_base .

          # Build and push synthetic_regression
          docker buildx build --push --tag $IMAGE_PREFIX/synthetic_regression:latest -f sciml_benchmarks/Dockerfile.synthetic_regression .

          # Build and push stemdl_classification_1gpu
          docker buildx build --push --tag $IMAGE_PREFIX/stemdl_classification_1gpu:latest -f sciml_benchmarks/Dockerfile.stemdl_classification_1gpu .

          # Build and push stemdl_classification_2gpu
          docker buildx build --push --tag $IMAGE_PREFIX/stemdl_classification_2gpu:latest -f sciml_benchmarks/Dockerfile.stemdl_classification_2gpu .

          # Build and push mnist_tf_keras
          docker buildx build --push --tag $IMAGE_PREFIX/mnist_tf_keras:latest -f sciml_benchmarks/Dockerfile.mnist_tf_keras .

          # Build and push mantid_run_8
          docker buildx build --push --tag $IMAGE_PREFIX/mantid_run_8:latest -f mantid_imaging_benchmarks/Dockerfile.mantid_run_8 .

          # Build and push mantid_run_1
          docker buildx build --push --tag $IMAGE_PREFIX/mantid_run_1:latest -f mantid_imaging_benchmarks/Dockerfile.mantid_run_1 .

          # Build and push dummy
          docker buildx build --push --tag $IMAGE_PREFIX/dummy:latest -f dummy/Dockerfile.dummy .
