name: Build and Push Docker Images

on:
  push:
    paths:
      - 'dockerfiles/**'
  pull_request:
    paths:
      - 'dockerfiles/**'
  workflow_dispatch:

jobs:
  build-base-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Build all images so we can see which fail
      matrix:
        image:
          [
            sciml_base,
            mantid_base
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Harbor, if building main
        uses: docker/login-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          registry: harbor.stfc.ac.uk
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
      
      - name: List files in base_images
        run: |
          ls -R ./dockerfiles/base_images

      - name: Build Base Images
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.ref == 'refs/heads/main' }}
          context: "./dockerfiles/base_images"
          dockerfile: "Dockerfile.${{ matrix.image }}"
          tags: "harbor.stfc.ac.uk/stfc-cloud/iris-bench/${{ matrix.image }}:latest"

  build-app-images:
    runs-on: ubuntu-latest
    needs: build-base-images

    strategy:
      fail-fast: false # Build all images so we can see which fail
      matrix:
        image:
          [
            synthetic_regression,
            mnist_tf_keras,
            stemdl_classification_1gpu,
            stemdl_classification_2gpu,
            synthetic_regression,
            mantid_run_1,
            mantid_run_8
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files in repository
        run: |
          ls -R

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Harbor, if building main
        uses: docker/login-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          registry: harbor.stfc.ac.uk
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Build Application Images
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.ref == 'refs/heads/main' }}
          context: "/iris-gpubench/dockerfiles/base_images"
          dockerfile: "Dockerfile.${{ matrix.image }}"
          tags: "harbor.stfc.ac.uk/stfc-cloud/iris-bench/${{ matrix.image }}:latest"
