name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'Benchmark_Dockerfiles/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan Dockerfiles and Build
        run: |
          # Create a list of Dockerfiles
          DOCKERFILES=$(find Benchmark_Dockerfiles -name 'Dockerfile*')

          for DOCKERFILE in $DOCKERFILES; do
            # Extract the Dockerfile extension and derive the image name
            EXTENSION=$(echo $DOCKERFILE | sed 's/.*Dockerfile\.//')
            IMAGE_NAME=${EXTENSION:-default}

            # Define the tag for the Docker image
            TAG="ghcr.io/${{ github.repository }}/$IMAGE_NAME:latest"

            echo "Building and pushing image: $TAG"

            # Build and push Docker image
            docker buildx build --push --tag $TAG -f $DOCKERFILE $(dirname $DOCKERFILE)
          done

      - name: Verify images
        run: |
          echo "Listing Docker images in the GitHub Container Registry"
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://ghcr.io/v2/${{ github.repository }}/tags/list"
